### ISSUE TITLE
Record from 5 seconds before motion detection

### ISSUE THREAD

**Issue by micksulley** [sandyol55/Ropey-Cam#2]
I wonder if you could help.  I have Ropey-Cam running, but I would like the video to capture from a few seconds before motion is detected.  From the documentation this is possible using CircularOutput.  I have modified the example "capture_circular_stream.py" 
and it works just as I want, however I have spent ages trying to add that feature to your code and just cannot figure out how to do it!
Could you help?
Thanks
Mick

**Comment by sandyol55** [comment]
I did have a 'predecessor' of this running with a circular buffer, but took that out for the version that became Ropey-Cam.  I'll have a look and see if it could be re-introduced.  Might take a while - got other things on the go at the moment!

**Comment by micksulley** [comment]
Thank you.  I am still trying to get a better understanding of how it all works, I will update if I make any progress.

**Comment by sandyol55** [comment]
Hi Mick,
I've got a version working with a circular buffer, but at the moment it's a bit messy and uses .H264 files rather than mp4, so isn't quite so handy for easy playback. Installing mpv media Player allows the files to be played back. If that's of use to you I'll try and tidy it up and upload as a separate python file - rather than as a replaced version of R-C?
EDIT: Now uploaded the circular buffer version, with, as described in the README, an inbuilt conversion to .mp4
Cheers
Sandy

**Comment by micksulley** [comment]
Hi Sandy,
Downloaded and installed the buffer version and it works!!!  
I need to do a few tweeks to get it to fit with what I need but the basis is there now. 
Many thanks for your help
Mick
